using System.Collections.Generic;

namespace HiddenGems.ApiResults
{
    public class ApiGetResultResult
    {
        /// <summary>
        /// Indicates the result of the request
        /// </summary>
        public string Message { get; set; }
        /// <summary>
        /// A <see cref="List{T}"/> of <see cref="KeyValuePair{TKey, TValue}"/> containing file names and \
        /// corresponding Base64-encoded file content generated by the submitJob request
        /// </summary>
        public List<KeyValuePair<string,string>> GeneratedFiles { get; set; }
    }
}
